# DEC-037: schema 3 native frontend, fail-closed registration and artifact gate.
if(NOT DEFINED REPO_ROOT OR (NOT DEFINED CASE AND NOT DEFINED BUILD_DIR))
    message(FATAL_ERROR "REPO_ROOT and BUILD_DIR are required")
endif()
if(DEFINED CASE)
    set(MIRAGE_DEPENDENCY_LOCK_DIR "${FIXTURE_DIR}")
    include("${REPO_ROOT}/cmake/MirageDependencies.cmake")
    _mirage_dependency_lock(lock_json)
    mirage_require_lock_schema("${lock_json}")
    mirage_validate_lock_extensions("${lock_json}")
    if(CASE STREQUAL "artifact")
        mirage_require_locked_artifact(cef retired)
    endif()
    return()
endif()
file(READ "${REPO_ROOT}/dependencies.lock.json" original)
set(fixture "${BUILD_DIR}/fixture")
file(MAKE_DIRECTORY "${fixture}/apps/native")
file(WRITE "${fixture}/apps/native/app.cpp" "// fixture\n")
function(check_case name body expected)
    file(WRITE "${fixture}/dependencies.lock.json" "${body}")
    execute_process(COMMAND "${CMAKE_COMMAND}" "-DREPO_ROOT=${REPO_ROOT}" "-DFIXTURE_DIR=${fixture}" "-DCASE=${name}" -P "${CMAKE_CURRENT_LIST_FILE}" RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error)
    if(expected STREQUAL "ok")
        if(NOT result EQUAL 0)
            message(FATAL_ERROR "${name} failed: ${output}${error}")
        endif()
    elseif(result EQUAL 0 OR NOT "${output}${error}" MATCHES "${expected}")
        message(FATAL_ERROR "${name} did not reject with '${expected}': ${output}${error}")
    endif()
endfunction()
check_case(valid "${original}" ok)
check_case(artifact "${original}" "not registered")
string(JSON invalid SET "${original}" schema_version 2)
check_case(old_schema "${invalid}" "schema_version must be 3")
string(JSON invalid SET "${original}" frontend kind "\"npm-tree\"")
check_case(old_frontend "${invalid}" "native-cpp")
string(JSON invalid REMOVE "${original}" frontend entry)
check_case(missing_entry "${invalid}" "missing required member")
string(JSON invalid SET "${original}" frontend entry "\"apps/desktop/main.cpp\"")
check_case(wrong_entry "${invalid}" "missing or invalid")
string(JSON invalid SET "${original}" frontend dependency "\"unlocked-ui\"")
check_case(wrong_dependency "${invalid}" "eui-neo")
file(REMOVE "${fixture}/apps/native/app.cpp")
check_case(absent_source "${original}" "missing or invalid")
file(WRITE "${fixture}/apps/native/app.cpp" "// fixture\n")
string(JSON invalid SET "${original}" artifacts "{}")
check_case(bad_artifacts "${invalid}" "artifacts must be an array")
message(STATUS "dependency_lock_gate_test: 9 cases passed")
