# Explicit development registration, not a side effect of an ordinary build.
if(NOT EXISTS "${MIRAGE_DESKTOP_ENTRY}")
    message(FATAL_ERROR "Build mirage-native before registering its desktop entry")
endif()
if(DEFINED ENV{XDG_DATA_HOME} AND NOT "$ENV{XDG_DATA_HOME}" STREQUAL "")
    set(mirage_data_home "$ENV{XDG_DATA_HOME}")
elseif(DEFINED ENV{HOME} AND NOT "$ENV{HOME}" STREQUAL "")
    set(mirage_data_home "$ENV{HOME}/.local/share")
else()
    message(FATAL_ERROR "Desktop registration requires XDG_DATA_HOME or HOME")
endif()
if(NOT IS_ABSOLUTE "${mirage_data_home}")
    message(FATAL_ERROR "XDG_DATA_HOME must be an absolute path")
endif()
file(MAKE_DIRECTORY "${mirage_data_home}/applications")
configure_file("${MIRAGE_DESKTOP_ENTRY}"
    "${mirage_data_home}/applications/org.mirage.native.desktop" COPYONLY)
find_program(mirage_desktop_database update-desktop-database)
if(mirage_desktop_database)
    execute_process(COMMAND "${mirage_desktop_database}" "${mirage_data_home}/applications"
        RESULT_VARIABLE mirage_refresh_result)
    if(NOT mirage_refresh_result EQUAL 0)
        message(FATAL_ERROR "Desktop database refresh failed: ${mirage_refresh_result}")
    endif()
endif()
message(STATUS "Registered ${mirage_data_home}/applications/org.mirage.native.desktop")
