#!/bin/bash
# M5-11 (DEC-006 决策 5 / DEC-031): build a GPG-signed apt repository from
# one or more Mirage .deb packages.
#
# Key isolation (shell-binary-locking 既定): the RELEASE signing key lives
# only on the release machine and is never generated by this script. For
# local rehearsal pass --test-key: an ephemeral key is generated inside the
# output tree's gnupg/ directory and clearly marked as non-release; the
# script FAILS CLOSED when no key material is available and --test-key is
# not given.
#
# Usage:
#   make-apt-repo.sh --out DIR --deb FILE [--deb FILE ...] [--suite NAME]
#                   [--origin NAME] [--test-key]
#   GPG key selection (release mode): GNUPGHOME + MIRAGE_GPG_KEY_ID env,
#   or the --key-id option.
set -eu

OUT=""
SUITE="stable"
ORIGIN="mirage"
KEY_ID=""
TEST_KEY=0
DEBS=()

while [ $# -gt 0 ]; do
    case "$1" in
    --out) OUT="$2"; shift 2 ;;
    --suite) SUITE="$2"; shift 2 ;;
    --origin) ORIGIN="$2"; shift 2 ;;
    --key-id) KEY_ID="$2"; shift 2 ;;
    --test-key) TEST_KEY=1; shift ;;
    --deb) DEBS+=("$2"); shift 2 ;;
    *) echo "unknown option: $1" >&2; exit 2 ;;
    esac
done

if [ -z "$OUT" ] || [ "${#DEBS[@]}" -eq 0 ]; then
    echo "usage: $0 --out DIR --deb FILE [--deb FILE ...] [--suite NAME] [--origin NAME] [--test-key]" >&2
    exit 2
fi
for deb in "${DEBS[@]}"; do
    [ -f "$deb" ] || { echo "not a file: $deb" >&2; exit 2; }
done

mkdir -p "$OUT"
REPO="$(cd "$OUT" && pwd)"

if [ "$TEST_KEY" -eq 1 ]; then
    # Local rehearsal only: ephemeral, non-release key inside the output
    # tree (never leaves it; never imported anywhere).
    GNUPG="$REPO/gnupg"
    export GNUPGHOME="$GNUPG"
    mkdir -p -m 700 "$GNUPGHOME"
    if ! gpg --list-secret-keys --with-colons 2>/dev/null | grep -q '^sec'; then
        gpg --batch --passphrase '' --quick-gen-key \
            "Mirage apt rehearsal (LOCAL TEST, NOT RELEASE)" ed25519 sign never
    fi
    KEY_ID=$(gpg --list-secret-keys --with-colons 2>/dev/null \
        | awk -F: '/^sec/ { print $5; exit }')
    echo "test key: $KEY_ID (local rehearsal, NOT the release key)"
elif [ -n "$KEY_ID" ]; then
    : # release key selected explicitly; GNUPGHOME points at the release keyring
elif [ -n "${MIRAGE_GPG_KEY_ID:-}" ]; then
    KEY_ID="${MIRAGE_GPG_KEY_ID}"
fi

if [ -z "$KEY_ID" ] && [ "$TEST_KEY" -ne 1 ]; then
    # Fail closed: no key material, no unsigned repo.
    echo "refusing to build an UNSIGNED repository: pass --test-key for local rehearsal" \
        "or provide the release key (GNUPGHOME / --key-id / MIRAGE_GPG_KEY_ID)" >&2
    exit 1
fi

# Pool: debs live under pool/<first-letter>/; apt-ftparchive writes the
# Packages index for the suite.
mkdir -p "$REPO/pool" "$REPO/dists/$SUITE/main/binary-amd64"
for deb in "${DEBS[@]}"; do
    letter="$(basename "$deb" | cut -c1 | tr 'A-Z' 'a-z')"
    mkdir -p "$REPO/pool/$letter"
    cp "$deb" "$REPO/pool/$letter/"
done

cd "$REPO"
apt-ftparchive packages pool > "dists/$SUITE/main/binary-amd64/Packages"
gzip -k -f "dists/$SUITE/main/binary-amd64/Packages"

cd "$REPO/dists/$SUITE"
cat > Release <<RELEASE_HEADER
Origin: $ORIGIN
Label: $ORIGIN
Suite: $SUITE
Codename: $SUITE
Architectures: amd64
Components: main
Description: Mirage apt repository ($SUITE)
RELEASE_HEADER
apt-ftparchive release . >> Release

# Sign: InRelease (clearsigned) + Release.gpg (detached). GnuPG requires a
# present config file in a fresh GNUPGHOME.
export GNUPGHOME="${GNUPGHOME:-$REPO/gnupg}"
mkdir -p -m 700 "$GNUPGHOME"
touch "$GNUPGHOME/.config-stamp"
gpg --batch --yes --local-user "$KEY_ID" --clearsign -o InRelease Release
gpg --batch --yes --local-user "$KEY_ID" --armor --detach-sign -o Release.gpg Release

echo "apt repository built at: $REPO"
echo "  signed by key: $KEY_ID"
exit 0
